# Generated by Django 5.2.8 on 2025-11-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.CharField(choices=[('PM2.5', 'PM2.5 (Fine Particulate Matter)'), ('NO2', 'NO2 (Nitrogen Dioxide)'), ('PM10', 'PM10 (Coarse Particulate Matter)'), ('O3', 'O3 (Ozone)'), ('SO2', 'SO2 (Sulfur Dioxide)')], max_length=50)),
                ('value', models.FloatField()),
                ('measured_at', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.school')),
            ],
            options={
                'verbose_name': 'Air Quality Reading',
                'verbose_name_plural': 'Air Quality Readings',
                'ordering': ['-measured_at'],
            },
        ),
    ]
